// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://staimtbbfkfexekkimiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0YWltdGJiZmtmZXhla2tpbWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4MDM3ODcsImV4cCI6MjA3ODM3OTc4N30.Gu6W-UngOWMC8dYOp8qBzKKR5k84Rn3ztYiyGrtE10w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);